var snek = [];
var snekLength = 3;
var foodX;
var foodY;
var xDir = 0;
var yDir = 1;
var interval = 100;
var speedCap = 80;
var timer;
var areaWidth = 20;
var areaHeight = 20;
var gridPixels = 20;
var backgroundColor = "#bbc1cc";
var snekColor = "#000000";
var foodColor = "#FF0000";
var xPos = areaWidth / 2;
var yPos = areaHeight / 2;
var growLength = 1;
var speedDelta = 5;
var score = 0;
var scoreIncrease = 10;
var scoreColor = "green";
var scoreFont = "30px Arial";
